const categoryData  = [
  {
    label: "Desktop",
    path: "/desktop",
    items: [
      { itemsLabel: "Start PC", itemsPath: "/star-pc" },
      { itemsLabel: "Gaming PC", itemsPath: "/gaming-pc" },
      { itemsLabel: "Brand PC", itemsPath: "/brand-pc" },
    ],
  },
  {
    label: "Monitor",
    path: "/monitor",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Component",
    path: "/component",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Office Equipment",
    path: "/Office-equipment",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Accessories",
    path: "/accessories",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Networking",
    path: "/networking",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Photocopier",
    path: "/photocopier",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Projector",
    path: "/projector",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Laptop Accessorises",
    path: "/laptopaccessorises",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Software",
    path: "/software",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Gaming",
    path: "/gaming",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
];
export default categoryData ;
