const categoryData = [
  {
    label: "Desktop",
    path: "/desktop",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fuploads%2Fall%2FEaq6ukjyiKKx5OtuBvq4RfdPSPg9hfjvd8KrqMc6.png&w=32&q=75",
    items: [
      { itemsLabel: "Start PC", itemsPath: "/star-pc" },
      { itemsLabel: "Gaming PC", itemsPath: "/gaming-pc" },
      { itemsLabel: "Brand PC", itemsPath: "/brand-pc" },
    ],
  },
  {
    label: "Monitor",
    path: "/monitor",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fuploads%2Fall%2FckmbhfKk6QHr0Qje5nRpPsP4akdLm64bMYYp4V1m.png&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Component",
    path: "/component",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fuploads%2Fall%2FIITXUELnEEOyTZkf2nfNNOVXz83OeuStONvJjQwN.png&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Vertical Graphics Card Holder", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Office Equipment",
    path: "/Office-equipment",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },

      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Accessories",
    path: "/accessories",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fuploads%2Fall%2F2hDEDeJyNqErEefV7P20c9dxSBDZqF7zABzn6bw1.png&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Networking",
    path: "/networking",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Photocopier",
    path: "/photocopier",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fuploads%2Fall%2FjtDBUjjY61btteO9ZonjGeeuzenfRaeeJbV5hEuU.png&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Projector",
    path: "/projector",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Laptop Accessorises",
    path: "/laptopaccessorises",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Software",
    path: "/software",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
  {
    label: "Gaming",
    path: "/gaming",
    icon: "https://allit.com.bd/_next/image?url=https%3A%2F%2Fallit.com.bd%3A81%2Fassets%2Fimg%2Fplaceholder.jpg&w=32&q=75",
    items: [
      { itemsLabel: "HP", itemsPath: "/star-pc" },
      { itemsLabel: "Dell", itemsPath: "/dell" },
      { itemsLabel: "Huawei", itemsPath: "/huawei" },
      { itemsLabel: "Samsung", itemsPath: "/Samsung" },
      { itemsLabel: "NPC", itemsPath: "/NPC" },
      { itemsLabel: "Hikvision", itemsPath: "/Hikvision" },
      { itemsLabel: "Gigasonic", itemsPath: "/Gigasonic" },
      { itemsLabel: "Lenovo", itemsPath: "/Lenovo" },
      { itemsLabel: "LG", itemsPath: "/LG" },
      { itemsLabel: "LGBenQ", itemsPath: "/LGBenQ" },
      { itemsLabel: "Viewsonic", itemsPath: "/Viewsonic" },
      { itemsLabel: "corsair", itemsPath: "/corsair" },
      { itemsLabel: "Philips", itemsPath: "/Philips" },
      { itemsLabel: "Walton", itemsPath: "/Walton" },
    ],
  },
];
export default categoryData;
